### ISSUE TITLE
your repo description could be misleading

### ISSUE THREAD

**Issue by mbourgey** [jmonlong/PopSV#4]
Hi Jean,

Your description: 'Population-based detection of structural variation from HTSeq', could be misleading because people can think that popSV uses count generated from the HTSeq software (http://www-huber.embl.de/users/anders/HTSeq/doc/overview.html). But I don't think this is the case.

Mathieu

**Comment by jmonlong** [comment]
Hi, 
By HTSeq, I meant High-Throughput Sequencing in general, but I understand the confusion. It's clarified now. 
Thanks for the feedback.
Jean

**Comment by mbourgey** [comment]
Now this perfect !
