### ISSUE TITLE
The question about installing manually

### ISSUE THREAD

**Issue by WortJohn** [jmonlong/PopSV#5]
When i install PopSV manually and the command is " install.packages('./PopSV-master.zip', repos=NULL)", the error that is "Error in rawToChar(block[seq_len(ns)]) :  The nul embeds into string : 'PK\003\004\n\0\0\0\0\0O\177\x86J\0\0\0\0\0\0\0\0\0\0\0\0\r\0\t\0PopSV-master/UT\005\0\001\026\xc8\xe6XPK\003\004\n\0\0\0\b\0O\177\x86J@\036\xdc/\030\0\0\0\032\0\0\0\027\0\t\0PopSV-master/.giti' " arises.

I don't have permission to install it through install_github, so i install it manually. But the error arises, please help me. Thank you!

**Comment by jmonlong** [comment]
To install manually with this command, you have to unzip `PopSV-master.zip` first and use the command on the unzipped folder, e.g. `install.packages('./PopSV-master', repos=NULL)`.

In theory you shouldn't need permissions to install a package (in your home). If the issue with `install_github` is something about *certificates*, then you may be able to install PopSV directly using `devtools::install_git("http://github.com/jmonlong/PopSV.git")`. This is an error I encountered in some computing clusters and the newest R versions.

Let me know if you have more troubles.

**Comment by WortJohn** [comment]
@jmonlong 
Thanks for your helps firstly.  I already install it successfully. But when i load it like "library(PopSV)",  the warning message that is "replacing previous import by ‘data.table::shift’ when loading ‘PopSV’" arises. I don't care it at first. But when i want to use the "fdrtool.quantile" function, the error whic is "no have the function" arises. Use it like your "fdr = fdrtool.quantile(z.df$z,quant.int=seq(.6,.99,.01))" from test-mergeBins.R. Is there some influence bewteen them?

**Comment by jmonlong** [comment]
Sorry for the late response. The function `fdrtool.quantile` is an internal function and you don't have to call it directly. The example you found is a unit test used to be sure that the package performs correctly, but not something that you should try to reproduce. 

The relevant function for this step of the analysis is `call.abnormal.cov` function.

For an example of the analysis and the functions you should use, see [this script](https://github.com/jmonlong/PopSV/blob/master/scripts/run-PopSV-local.R). `call.abnormal.cov` is called in step 8.

In practice, I would recommend using the automated pipeline and a computing cluster. That way you don't have to deal with all the steps and the jobs are taken care automatically. Don't hesitate if you need assistance.
