### ISSUE TITLE
Problem installing dependencies

### ISSUE THREAD

**Issue by Addicted-to-coding** [jmonlong/PopSV#9]
When I try to install the Bioconductor packages with the command 
source("http://bioconductor.org/biocLite.R")
biocLite("BSgenome.Hsapiens.UCSC.hg19", "Rsamtools", "DNAcopy", "rtracklayer")
I get the error:
Error in !suppressAutoUpdate : invalid argument type

How can I solve this?

**Comment by jmonlong** [comment]
Oh you're right, it seems that this syntax doesn't work anymore. Please use this instead:

```
 biocLite(c("BSgenome.Hsapiens.UCSC.hg19", "Rsamtools", "DNAcopy", "rtracklayer"))
```

I'll update the documentation, thanks for raising the issue.

**Comment by Addicted-to-coding** [comment]
Thanks a lot for the prompt response, it works now!
